name: beissab_mobile
description: Native Flutter client for BeissAb.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  go_router: ^14.2.7
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/brand/
    - assets/images/
